### ISSUE TITLE
utemplate not found on my ESP32 micropython

### ISSUE THREAD

**Issue by aka-engineer** [donskytech/micropython-web-server-microdot#2]
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "microdot_utemplate.py", line 1, in <module>
ImportError: no module named 'utemplate'

**Comment by Ariel-Ohayon** [comment]
Hello,
I also encountered the same problem.
The solution I found is to download the 'utemplate' package directly from the following link.
[https://github.com/pfalcon/utemplate/tree/master](url)
This is actually a directory containing three files, you need to save them in a directory on your micropython device called 'utemplate' and then it should work fine.
